# 사칙 연산
x = int(input("정수x값을 입력하세요  "))
y = int(input("정수y값을 입력하세요  "))
print("덧셈은 ", x + y, "입니다.")
print("뻴셈은 ", x - y, "입니다.")
print("곱셈은 ", x * y, "입니다.")
print("나눗셈은 ", x / y, "입니다.")
print("몫은 ", x // y, "입니다.")
print("나머지는 ", x % y, "입니다.")
print("제곱값은 ", x ** y, "입니다.")
print ()
print (x == y)
print (x != y)
print (x >= y)
print (x <= y)
print (x > y)
print (x < y)
